import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import *
import Stockage
from PyQt5 import QtGui
from PyQt5.QtCore import QDate
from qtconsole.qt import QtCore
from qtpy import QtWidgets


class Accueil_test(QWidget):
    """Classe représentant le formulaire de saisie d'ajout d'un equipement"""

    def __init__(self, Form, parent=None):
        QWidget.__init__(self, Form, parent)

        Form.setObjectName("Form")
        Form.resize(752, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pc2-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ajouterUnEquipementButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ajouterUnEquipementButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ajouterUnEquipementButton.setIcon(icon1)
        self.ajouterUnEquipementButton.setIconSize(QtCore.QSize(40, 40))
        self.ajouterUnEquipementButton.setObjectName("ajouterUnEquipementButton")
        self.horizontalLayout.addWidget(self.ajouterUnEquipementButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.consulterUnEquipementButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.consulterUnEquipementButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("view-icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consulterUnEquipementButton.setIcon(icon2)
        self.consulterUnEquipementButton.setIconSize(QtCore.QSize(40, 40))
        self.consulterUnEquipementButton.setObjectName("consulterUnEquipementButton")
        self.horizontalLayout.addWidget(self.consulterUnEquipementButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.modifierUnEquipementButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.modifierUnEquipementButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Modify-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modifierUnEquipementButton.setIcon(icon3)
        self.modifierUnEquipementButton.setIconSize(QtCore.QSize(40, 40))
        self.modifierUnEquipementButton.setObjectName("modifierUnEquipementButton")
        self.horizontalLayout.addWidget(self.modifierUnEquipementButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bonDeTravailButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bonDeTravailButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("view-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bonDeTravailButton.setIcon(icon4)
        self.bonDeTravailButton.setIconSize(QtCore.QSize(70, 70))
        self.bonDeTravailButton.setObjectName("bonDeTravailButton")
        self.horizontalLayout_2.addWidget(self.bonDeTravailButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.baseDeDonneesButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.baseDeDonneesButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("database-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.baseDeDonneesButton.setIcon(icon5)
        self.baseDeDonneesButton.setIconSize(QtCore.QSize(50, 50))
        self.baseDeDonneesButton.setObjectName("baseDeDonneesButton")
        self.horizontalLayout_5.addWidget(self.baseDeDonneesButton)
        self.inventaireButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inventaireButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("inventory_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inventaireButton.setIcon(icon6)
        self.inventaireButton.setIconSize(QtCore.QSize(50, 50))
        self.inventaireButton.setObjectName("inventaireButton")
        self.horizontalLayout_5.addWidget(self.inventaireButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rechercherUnEquipementButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rechercherUnEquipementButton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("search-icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rechercherUnEquipementButton.setIcon(icon7)
        self.rechercherUnEquipementButton.setIconSize(QtCore.QSize(50, 50))
        self.rechercherUnEquipementButton.setObjectName("rechercherUnEquipementButton")
        self.horizontalLayout_3.addWidget(self.rechercherUnEquipementButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.rechercherUnBonDeTravailButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rechercherUnBonDeTravailButton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Search-icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rechercherUnBonDeTravailButton.setIcon(icon8)
        self.rechercherUnBonDeTravailButton.setIconSize(QtCore.QSize(50, 50))
        self.rechercherUnBonDeTravailButton.setObjectName("rechercherUnBonDeTravailButton")
        self.horizontalLayout_3.addWidget(self.rechercherUnBonDeTravailButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.s = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.s.setFont(font)
        self.s.setIcon(icon)
        self.s.setIconSize(QtCore.QSize(100, 100))
        self.s.setObjectName("s")
        self.horizontalLayout_3.addWidget(self.s)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hatim"))
        self.label.setText(_translate("Form", "                                 S.I.M.M. 2.0 \n"
                                              "Système d'Inventorisation de Matériel Médical"))
        self.ajouterUnEquipementButton.setText(_translate("Form", "Ajouter un Équipement  "))
        self.consulterUnEquipementButton.setText(_translate("Form", "Consulter un Équipement  "))
        self.modifierUnEquipementButton.setText(_translate("Form", "Modifier un Équipement  "))
        self.bonDeTravailButton.setText(_translate("Form", "Consulter - Ajouter un Bon de Travail"))
        self.baseDeDonneesButton.setText(_translate("Form", "Base de Données"))
        self.inventaireButton.setText(_translate("Form", "Inventaire"))
        self.rechercherUnEquipementButton.setText(_translate("Form", "Rechercher un Équipement"))
        self.rechercherUnBonDeTravailButton.setText(_translate("Form", "Rechercher un Bon de Travail"))
        self.s.setText(_translate("Form", "Support"))

if __name__ == "__main__":

    app = QApplication(sys.argv)

    win = Accueil_test()
    win.setWindowTitle("Options")

    win.show()

    sys.exit(app.exec_())